export default [
  {
    id: 1,
    customer: 'Leslie Knope',
    email: 'knope.leslie@email.com',
    openDate: '3-1-22',
    status: 'active',
    stagesTotalCount: 5,
    stagesCompletedCount: 3,
    link: '',
  },
  {
    id: 2,
    customer: 'Ron Swanson',
    email: 'swanson.ron@email.com',
    openDate: '6-1-22',
    status: 'active',
    stagesTotalCount: 8,
    stagesCompletedCount: 2,
    link: '',
  },
  {
    id: 3,
    customer: 'Ben Wyatt',
    email: 'wyatt.ben@email.com',
    openDate: '10-1-22',
    status: 'active',
    stagesTotalCount: 8,
    stagesCompletedCount: 4,
    link: '',
  },
  {
    id: 4,
    customer: 'Andy Dwyer',
    email: 'dwyer.andy@email.com',
    openDate: '22-1-22',
    status: 'complete',
    stagesTotalCount: 6,
    stagesCompletedCount: 6,
    link: '',
  },
  {
    id: 5,
    customer: 'April Ludgate',
    email: 'ludgate.april@email.com',
    openDate: '28-1-22',
    status: 'active',
    stagesTotalCount: 5,
    stagesCompletedCount: 4,
    link: '',
  },
  {
    id: 6,
    customer: 'Jean-Ralphio',
    email: 'ralphio.jean@email.com',
    openDate: '3-2-22',
    status: 'active',
    stagesTotalCount: 10,
    stagesCompletedCount: 3,
    link: '',
    isClosed: true,
  },
  {
    id: 7,
    customer: 'Ann Perkins',
    email: 'perkins.ann@email.com',
    openDate: '4-2-22',
    status: 'complete',
    stagesTotalCount: 5,
    stagesCompletedCount: 5,
    link: '',
  },
  {
    id: 8,
    customer: 'Jerry Gergich',
    email: 'gergich.jerry@email.com',
    openDate: '6-2-22',
    status: 'complete',
    stagesTotalCount: 5,
    stagesCompletedCount: 5,
    link: '',
    isClosed: true,
  },
  {
    id: 9,
    customer: 'Chris Traeger',
    email: 'traeger.chris@email.com',
    openDate: '6-2-22',
    status: 'active',
    stagesTotalCount: 7,
    stagesCompletedCount: 5,
    link: '',
  },
  {
    id: 10,
    customer: 'Tom Haverford',
    email: 'haverford.tom@email.com',
    openDate: '9-2-22',
    status: 'complete',
    stagesTotalCount: 4,
    stagesCompletedCount: 4,
    link: '',
  },
  {
    id: 11,
    customer: 'Donna Meagle',
    email: 'meagle.donna@email.com',
    openDate: '12-2-22',
    status: 'active',
    stagesTotalCount: 5,
    stagesCompletedCount: 4,
    link: '',
  },
  {
    id: 12,
    customer: 'Jeremy Jamm',
    email: 'jamm.jeremy@email.com',
    openDate: '1-3-22',
    status: 'complete',
    stagesTotalCount: 4,
    stagesCompletedCount: 4,
    link: '',
  },
]
